package com.brahamchari.demoplugin.repository

import com.android.ddmlib.AndroidDebugBridge
import com.android.ddmlib.IDevice
import com.brahamchari.demoplugin.client.MCPClient
import com.brahamchari.demoplugin.client.ProcessResult
import com.brahamchari.demoplugin.client.QueryResult
import com.brahamchari.demoplugin.di.TestCaseInjector
import com.brahamchari.demoplugin.models.*
import com.brahamchari.demoplugin.services.McpService
import com.brahamchari.demoplugin.services.TestLogPersistenceService
import com.brahamchari.demoplugin.services.TestLogPersistenceServiceImpl
import com.brahamchari.demoplugin.utils.ADBUtils
import com.brahamchari.demoplugin.utils.PromptGenerator
import com.brahamchari.demoplugin.utils.Utils
import com.google.gson.Gson
import com.google.gson.JsonSyntaxException
import com.intellij.openapi.Disposable
import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.diagnostic.Logger
import com.intellij.openapi.project.Project
import com.intellij.openapi.util.Disposer
import kotlinx.coroutines.*
import kotlinx.coroutines.channels.ChannelResult
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.channels.onFailure
import kotlinx.coroutines.flow.*
import java.awt.Rectangle
import java.io.File
import java.util.UUID
import kotlin.random.Random

interface TestCaseRepository {
    var isTestRunning: Boolean

    fun runTestCase(testId: String, textInput: String, deviceId: String, model: AiModelData): Flow<TestExecutionLog>

    suspend fun stopRunningTest()

    /**
     * Provides a Flow that emits the current list of connected ADB devices
     * whenever the list changes. The flow handles the underlying ADB listener.
     * Emits an empty list if ADB is unavailable or an error occurs during fetch.
     */
    fun getAdbDevicesFlow(): Flow<List<IDevice>>

    /**
     * Saves the details of a completed test execution log using the persistence service.
     * @param logData The complete log data to save.
     * @return A Result containing the path (String) to the saved file on success,
     * or an Exception on failure.
     */
    suspend fun saveExecutionLog(logData: TestExecutionLog): Result<String>

    /**
     * Loads all previously saved test execution logs for the current project.
     * @return A Result containing the List of logs on success, or an Exception on failure.
     */
    suspend fun loadExecutionLogs(): Result<List<TestExecutionLog>> // Added load method

    /**
     * Replays a given list of test steps by executing the tool calls found within them.
     * Emits the state of the replay's own TestExecutionLog as it progresses.
     *
     * @param replayLogId A unique ID generated by the caller for this specific replay attempt.
     * @param deviceId The target device ID for replay.
     * @param originalLog The original TestExecutionLog containing the steps to replay.
     * @return A Flow emitting TestExecutionLog objects reflecting the state of the replay attempt.
     */
    suspend fun replayTestSteps(replayLogId: String, deviceId: String, originalLog: TestExecutionLog, model: AiModelData): Flow<TestExecutionLog>

    fun testFun(deviceId: String)
}

class TestCaseRepositoryImpl(
    private val project: Project,
    parentDisposable: Disposable
) : TestCaseRepository {

    private val log = Logger.getInstance(TestCaseRepositoryImpl::class.java)

    private var currentTestJob: Job? = null

    private val gson: Gson by lazy { TestCaseInjector.getTestCaseInjector().gson }
    private val repositoryScope by lazy { CoroutineScope(SupervisorJob() + Dispatchers.Default) }
    private val mcpService: McpService by lazy { TestCaseInjector.getTestCaseInjector().getMCPService(project) }

    private val persistenceService: TestLogPersistenceService by lazy {
        ApplicationManager.getApplication().getService(TestLogPersistenceServiceImpl::class.java)
            ?: run { // Execute this block if getService returns null
                val errorMsg =
                    "FATAL ERROR: TestLogPersistenceService not found. Ensure it's registered correctly in plugin.xml."
                log.error(errorMsg)
                throw IllegalStateException(errorMsg)
            }
    }

    init {
        Disposer.register(parentDisposable) {
            log.info("Disposing TestCaseRepositoryImpl, cancelling scope.")
            repositoryScope.cancel("Repository instance disposed.")
        }
    }

    @Volatile
    override var isTestRunning: Boolean = false

    override fun runTestCase(
        testId: String,
        textInput: String,
        deviceId: String,
        model: AiModelData
    ): Flow<TestExecutionLog> = channelFlow {
        val testExecutionLog = TestExecutionLog(
            id = testId,
            userInput = textInput,
            startTime = System.currentTimeMillis(),
            status = TestStatus.RUNNING,
            isSaved = false
        )

        if (isTestRunning) {
            trySend(
                testExecutionLog.copy(
                    status = TestStatus.FAILED,
                    error = ExecutionError(message = "Test is already running")
                )
            )
            close(IllegalStateException("Test is already running"))
            return@channelFlow
        }

        var serviceInitStatus = true
        if (!mcpService.isServiceRunning) {
            log.info("MCP Service not running, attempting to initialize...")
            serviceInitStatus = mcpService.initializeAndStart()
        }
        if (!serviceInitStatus) {
            log.error("MCP Service unavailable")
            trySend(
                testExecutionLog.copy(
                    status = TestStatus.FAILED,
                    error = ExecutionError(message = "Request service (MCP) unavailable")
                )
            )
            close(IllegalStateException("MCP Service unavailable"))
            return@channelFlow
        }

        isTestRunning = true
        log.info("\n\n\n\nRun Test case started for input: '$textInput'\n\n\n\n")

        currentTestJob = repositoryScope.launch(Dispatchers.IO) {
            var loopError: Exception? = null
            try {
                testExecutionLog.executionResult = ExecutionResult(
                    introduction = getTestIntro(textInput, deviceId, model),
//                    introduction = getTestIntroDemo(textInput, deviceId),
                    llmUsed = model.modelName,
                    targetDeviceId = deviceId,
                    testSteps = mutableListOf()
                )
                trySend(testExecutionLog.copy())

                do {
                    val currentStepNumber = (testExecutionLog.executionResult?.testSteps?.size ?: 0) + 1
                    log.info("\n\nRunning step $currentStepNumber")

                    val mcpResponse = makeMCPCall(testExecutionLog, deviceId, 2, model)
//                    val mcpResponse = makeMCPCallDemo(testExecutionLog, deviceId)
                    testExecutionLog.executionResult?.testSteps?.add(mcpResponse)
                    testExecutionLog.status = when(mcpResponse.outcome) {
                        StepOutcome.SUCCESS -> TestStatus.PASSED
                        StepOutcome.FAILURE -> TestStatus.FAILED
                        StepOutcome.CONTINUE -> TestStatus.RUNNING
                        StepOutcome.ERROR -> {
                            val errorMessage = mcpResponse.errorMessage ?: "Error while processing step: ${mcpResponse.title}"
                            loopError = Exception(errorMessage)
                            testExecutionLog.error = ExecutionError(errorMessage)
                            TestStatus.FAILED
                        }
                    }

                    trySend(testExecutionLog.copy())
                    log.info("Emitted step $currentStepNumber ${mcpResponse.title}. FinalStatus: ${testExecutionLog.status}\n\n")
                    delay(150) // Optional delay between steps
                } while (testExecutionLog.status == TestStatus.RUNNING && isActive)

            } catch (e: CancellationException) {
                log.info("Test execution job cancelled for input: '$textInput'.")
                loopError = e
            } catch (e: Exception) {
                log.error("Exception during test execution loop for input: '$textInput'.", e)
                loopError = e
            } finally {
                log.info("Finishing test execution job for input: '$textInput'.")
                isTestRunning = false

                if (isActive) {
                    if (loopError != null && loopError !is CancellationException) {
                        testExecutionLog.status = TestStatus.FAILED
                        testExecutionLog.error = ExecutionError(loopError.message ?: "Test failed due to exception")
                    } else if (loopError is CancellationException) {
                        testExecutionLog.status = TestStatus.STOPPED
                        testExecutionLog.error = ExecutionError("Test stopped by user")
                    }
                    trySend(testExecutionLog.copy())
                    log.info("Sent final log state: ${testExecutionLog.status}")
                } else {
                    log.warn("Flow/Scope became inactive before final state could be sent.")
                }
                // Close the flow from the producer side upon completion or error
                close(loopError) // Use default close handling
            }
        }

        // Cleanup: Cancel the job if the flow collector stops collecting
        awaitClose {
            log.warn("Test execution flow closing (awaitClose).")
            isTestRunning = false // Ensure flag is reset
            if (currentTestJob?.isActive == true) {
                log.info("Cancelling active test job due to flow closure.")
                currentTestJob?.cancel(CancellationException("Flow collection stopped."))
            }
        }
    }.flowOn(Dispatchers.IO)

    override suspend fun replayTestSteps(
        replayLogId: String,
        deviceId: String,
        originalLog: TestExecutionLog,
        model: AiModelData
    ): Flow<TestExecutionLog> = flow {
        val stepsToReplay = originalLog.executionResult?.testSteps?.sortedBy { it.timestamp } ?: emptyList()
        log.info("[Replay $replayLogId] Starting replay of ${stepsToReplay.size} steps on device $deviceId")

        val userInput = if (originalLog.userInput.startsWith("[Replay]")) originalLog.userInput else "[Replay] " + originalLog.userInput

        // --- Create the NEW log object for this replay attempt ---
        val replayLog = TestExecutionLog(
            id = replayLogId, // Use the passed-in ID
            userInput = userInput, // Copy original input
            startTime = System.currentTimeMillis(),
            status = TestStatus.RUNNING, // Start in running state
            isSaved = false, // Replays aren't saved by default
            executionResult = ExecutionResult(
                introduction = "Replaying ${stepsToReplay.size} recorded step(s)...\n${originalLog.executionResult?.introduction}", // Duplicate intro?
                llmUsed = "Replay (No AI)", // Indicate no LLM used
                targetDeviceId = deviceId,
                testSteps = mutableListOf() // IMPORTANT: Use mutable list here
            ),
        )

        try {
            emit(replayLog.copy()) // Signal loading start

            var serviceInitStatus = true
            if (!mcpService.isServiceRunning) {
                log.info("MCP Service not running, attempting to initialize...")
                serviceInitStatus = mcpService.initializeAndStart()
            }
            if (!serviceInitStatus) {
                log.error("MCP Service unavailable")
                throw IllegalStateException("MCP Service unavailable")
            }

            if (stepsToReplay.isEmpty()) {
                log.warn("[Replay $replayLogId] No steps found to replay.")
                replayLog.status = TestStatus.FAILED
                replayLog.error = ExecutionError("Original test log contained no steps to replay.")
                replayLog.endTime = System.currentTimeMillis()
                emit(replayLog.copy()) // Emit final failure state
                return@flow
            }

            for ((stepIndex, originalStep) in stepsToReplay.withIndex()) {
                if (!currentCoroutineContext().isActive) break // Check for cancellation before each step
                val stepNum = stepIndex + 1

                if(originalStep.actions == null) continue

                val currentReplayStep = originalStep.copy(
                    id = UUID.randomUUID().toString(),
                    timestamp = System.currentTimeMillis(),
                    title = "Step $stepNum",
                    outcome = StepOutcome.CONTINUE,
                )

                currentReplayStep.screenshotPath = captureAndGetScreenshotPath(stepNum, deviceId)
                delay(200) // Small delay

                val currentActions = mutableListOf<Action>()
                for(action in originalStep.actions!!) {
                    currentActions.add(action)
                    currentReplayStep.actions = currentActions
                    val toolActionToExecute = action.toolInfo

                    try {
                        if (toolActionToExecute != null) {
                            val toolResult =
                                mcpService.mcpClient.callTool(toolActionToExecute.toolName, toolActionToExecute.toolArguments)

                            if (toolResult.isFailure) { throw toolResult.exceptionOrNull()!! }
                            currentReplayStep.outcome = originalStep.outcome
                            currentReplayStep.errorMessage = originalStep.errorMessage
                        }
                    } catch (e: CancellationException) {
                        log.info("[Replay $replayLogId] Cancelled during step $stepNum")
                        currentReplayStep.outcome = StepOutcome.ERROR
                        currentReplayStep.errorMessage = "Replay stopped"
                        currentReplayStep.title = "Step $stepNum: Stopped"
                        replayLog.status = TestStatus.STOPPED
                        replayLog.error = ExecutionError("Test Cancelled by User")
                        replayLog.executionResult?.testSteps?.add(currentReplayStep)
                        throw e
                    } catch (e: Exception) {
                        log.error("[Replay $replayLogId] Failed step $stepNum: ${e.message}", e)
                        currentReplayStep.outcome = StepOutcome.FAILURE
                        currentReplayStep.errorMessage = e.message ?: "Step execution failed"
                        currentReplayStep.title = "Step $stepNum: Failed"
                        replayLog.status = TestStatus.FAILED
                        replayLog.error = ExecutionError("Exception occurred: ${e.message}")
                        replayLog.executionResult?.testSteps?.add(currentReplayStep)
                        throw e
                    }
                }

                if (currentCoroutineContext().isActive) {
                    if(stepIndex >= (stepsToReplay.size - 1)) {
                        currentReplayStep.outcome = StepOutcome.CONTINUE
                    }
                    replayLog.executionResult?.testSteps?.add(currentReplayStep)
                    emit(replayLog)
                }
            }

            // --- Final Emission ---
            if (currentCoroutineContext().isActive) {
                val stepNumber = (replayLog.executionResult?.testSteps?.size ?: 0) + 1

                val mcpResponse = makeMCPCall(replayLog, deviceId, 2, model)
                mcpResponse.title = "Step $stepNumber: Verification of Test"
                replayLog.executionResult?.testSteps?.add(mcpResponse)
                replayLog.status = when(mcpResponse.outcome) {
                    StepOutcome.SUCCESS -> TestStatus.PASSED
                    StepOutcome.FAILURE -> TestStatus.FAILED
                    StepOutcome.CONTINUE -> TestStatus.RUNNING
                    StepOutcome.ERROR -> {
                        val errorMessage = mcpResponse.errorMessage ?: "Error while processing step: ${mcpResponse.title}"
                        replayLog.error = ExecutionError(errorMessage)
                        TestStatus.FAILED
                    }
                }
                replayLog.endTime = System.currentTimeMillis()

                emit(replayLog.copy())
                log.info("Emitted step $stepNumber. FinalStatus: ${replayLog.status}\n\n")
            }
        } catch (e: CancellationException) {
            replayLog.status = TestStatus.STOPPED
            replayLog.error = ExecutionError("Replay Test stopped by User.")
        } catch (e: Exception) {
            replayLog.status = TestStatus.STOPPED
            replayLog.error = ExecutionError("Replay failed: ${e.message}")
        } finally {
            replayLog.endTime = System.currentTimeMillis()
            emit(replayLog)
        }
    }.flowOn(Dispatchers.IO)

    override fun testFun(deviceId: String) {
        repositoryScope.launch {
        }
    }

    private fun mapToActions(queryResult: List<QueryResult>): Pair<StepOutcome, List<Action>> {
        var actionFeedback = StepOutcome.CONTINUE
        val actions = queryResult.map { block ->
            val actionContext = block.textResult
                ?.takeIf { it.isNotBlank() }
                ?.let { jsonText ->
                    try {
                        val actionContext = gson.fromJson(jsonText, ActionContext::class.java)
                        actionFeedback = when(actionContext.feedback) {
                            ActionFeedback.PASS -> StepOutcome.SUCCESS
                            ActionFeedback.FAIL -> StepOutcome.FAILURE
                            ActionFeedback.CONTINUE -> StepOutcome.CONTINUE
                        }
                        actionContext
                    } catch (e: Exception) {
                        log.warn("Failed to parse ActionContext JSON: $jsonText", e)
                        null
                    }
                }
            val toolInfo = block.toolCallInfo?.let { tcInfo ->
                ToolInfo(tcInfo.toolName, tcInfo.inputArgumentsJson)
            }
            Action(actionContext, toolInfo)
        }

        return Pair(actionFeedback, actions)
    }

    private suspend fun makeMCPCall(
        testExecutionLog: TestExecutionLog,
        deviceId: String,
        retries: Int = 2,
        model: AiModelData
    ): TestStep {
        val testSteps = testExecutionLog.executionResult?.testSteps
        val currentStepIndex = testSteps?.size ?: 0
        val stepNumber = currentStepIndex + 1

        val currentTestStep = TestStep(
            id = UUID.randomUUID().toString(),
            title = "Step $stepNumber",
            timestamp = System.currentTimeMillis(),
            screenshotPath = null,
            outcome = StepOutcome.CONTINUE
        )

        if (retries <= 0) {
            log.warn("MCP Call failed after all retries for test: ${testExecutionLog.userInput} Step: $stepNumber")
            currentTestStep.outcome = StepOutcome.ERROR
            currentTestStep.title = "Step $stepNumber: Failed (Retries Exhausted)"
            currentTestStep.errorMessage = "AI/MCP call failed after multiple retries."
            return currentTestStep
        }

        try {
            currentTestStep.screenshotPath = captureAndGetScreenshotPath(stepNumber, deviceId)
            val screenCtxJson: String = getScreenCtxJson(deviceId)

            log.info("Making MCP call for test '${testExecutionLog.userInput}', Step $stepNumber, Try ${3 - retries}")

            val previousStepsContext = gson.toJson(testSteps?.map { it.actions } ?: "No previous steps")
            val lastMCPStep = gson.toJson(testSteps?.lastOrNull() ?: "No last step")
            val mcpClient = mcpService.mcpClient

            if(mcpClient.isConnected) {
                val systemPrompt = PromptGenerator.getActionSystemPromptGemini()
                val userPrompt = PromptGenerator.getActionUserPromptGemini(testExecutionLog.userInput, screenCtxJson, lastMCPStep, previousStepsContext)

                when(val mcpResult = mcpClient.processQuery(userPrompt, systemPrompt, model)) {
                    is ProcessResult.Error -> throw Exception("MCP processing error: ${mcpResult.exception.message}")
                    is ProcessResult.Success -> {
                        return try {
                            val (stepOutcome, actions) = mapToActions(mcpResult.queryResult)
                            currentTestStep.apply {
                                this.actions = actions
                                this.outcome = stepOutcome
                            }
                        } catch (e: JsonSyntaxException) {
                            log.error("Failed to parse ActionContext JSON from MCP for step $stepNumber: ${mcpResult.queryResult}", e)
                            currentTestStep.outcome = StepOutcome.ERROR
                            currentTestStep.errorMessage = "Failed to parse AI action JSON: ${e.message}"
                            currentTestStep.title = "Step $stepNumber: Error (Parse Failed)"
                            currentTestStep
                        }
                    }
                }
            } else {
                throw IllegalStateException("MCP Server not connected.")
            }
        } catch (e: Exception) {
            log.warn("Exception during makeMCPCall (try ${3 - retries}) for step $stepNumber: ${e.message}", e)

            if (e is CancellationException) {
                log.info("MCP call for step $stepNumber cancelled.")
                currentTestStep.outcome = StepOutcome.ERROR // Or a specific CANCELLED state?
                currentTestStep.errorMessage = "Operation cancelled during step $stepNumber."
                currentTestStep.title = "Step $stepNumber: Cancelled"
                return currentTestStep // Don't retry if cancelled
            }

            log.warn("Retrying MCP call for step $stepNumber (${retries - 1} retries left)...")
            val delayMillis = 500L
            delay(delayMillis)
            return makeMCPCall(testExecutionLog, deviceId, retries - 1, model)
        }
    }

    private suspend fun captureAndGetScreenshotPath(stepNumber: Int, deviceId: String) = try {
        withContext(Dispatchers.IO) { // Ensure ADB calls are off main thread
            val screenshotName = "screenshot_${System.currentTimeMillis()}_step${stepNumber}"
            ADBUtils.captureAndGetScreenshotPath(deviceId, screenshotName)
        }
    } catch (e: Exception) {
        log.error("Failed to capture screenshot for step $stepNumber", e)
        null
    }

    private suspend fun makeMCPCallDemo(
        testExecutionLog: TestExecutionLog,
        deviceId: String,
        retries: Int = 2 // Parameter kept for signature match
    ): TestStep {
        val existingSteps = testExecutionLog.executionResult?.testSteps ?: emptyList()
        val currentStepIndex = existingSteps.size
        val stepNumber = currentStepIndex + 1

        log.info("[DEMO] Simulating MCP call for Step $stepNumber...")

        // Simulate network/processing delay
        delay(800L + Random.nextLong(700)) // Simulate 0.8 - 1.5 seconds

        // --- Simulate different outcomes based on step number ---
        // You can customize this logic for more complex simulations
        val simulatedOutcome: StepOutcome
        val simulatedActionContext: ActionContext

        val maxDemoSteps = 4 // Example: Simulate 4 steps then PASS
        if (stepNumber < maxDemoSteps) {
            // Simulate CONTINUE with a plausible action
            simulatedOutcome = StepOutcome.CONTINUE
            simulatedActionContext = ActionContext(
                context = "Simulated action for Step $stepNumber: Find and click button 'next_button_$stepNumber'",
                feedback = ActionFeedback.CONTINUE, // Important: Map correctly later
                resourceId = "com.example.app:id/next_button_$stepNumber"
            )
        } else if (stepNumber == maxDemoSteps) {
            // Simulate PASS on the target step
            simulatedOutcome = StepOutcome.SUCCESS // Corresponds to ActionFeedback.PASS
            simulatedActionContext = ActionContext(
                context = "Simulated final verification for Step $stepNumber. Required element found.",
                feedback = ActionFeedback.PASS, // Final PASS
                resourceId = "com.example.app:id/success_indicator"
            )
        } else {
            // Should not be reached if PASS/FAIL stops the loop, but as fallback:
            simulatedOutcome = StepOutcome.FAILURE
            simulatedActionContext = ActionContext(
                context = "Simulated unexpected state after step ${stepNumber-1}. Failing.",
                feedback = ActionFeedback.FAIL,
                resourceId = null
            )
        }
        // --- End Simulation Logic ---

        // Create the Action object wrapping the context
        val action = Action(actionContext = simulatedActionContext, toolInfo = null)

        // Create the final TestStep object for this simulated step
        val currentTestStep = TestStep(
            id = UUID.randomUUID().toString(),
            title = "Step $stepNumber: ${simulatedActionContext.context.take(50)}...", // Use AI context for title
            timestamp = System.currentTimeMillis(),
            screenshotPath = null, // Simulate no screenshot for simplicity, or add dummy path
            outcome = simulatedOutcome,
            actions = listOf(action), // Assign the simulated action
            errorMessage = if (simulatedOutcome == StepOutcome.FAILURE) "Simulated failure occurred" else null
        )

        log.info("[DEMO] Simulated MCP call result for Step $stepNumber: Outcome=$simulatedOutcome")
        return currentTestStep
    }


    private suspend fun getTestIntro(textInput: String, deviceId: String, model: AiModelData): String {
        return try {
            val screenCtxJson = getScreenCtxJson(deviceId)
            if (mcpService.mcpClient.isConnected) {
                val userPrompt = PromptGenerator.getIntroductionUserPrompt(textInput, screenCtxJson)
                val systemPrompt = PromptGenerator.getIntroductionSystemPrompt()
                return when(val queryResult = mcpService.mcpClient.processQuery(userPrompt, systemPrompt, model)) {
                    is ProcessResult.Error -> throw queryResult.exception
                    is ProcessResult.Success -> {
                        queryResult.queryResult[0].textResult ?: throw Exception("Unable to generate introduction")
                    }
                }
            } else {
                throw Exception("MCP Service is unavailable")
            }
        } catch (e: Exception) {
            log.error("getTestIntro(): Error - ${e.message}", e)
            "Unable to generate introduction. Processing test: $textInput"
        }
    }

    private suspend fun getTestIntroDemo(textInput: String, deviceId: String): String {
        log.info("[DEMO] Simulating fetching Introduction for: '$textInput'")

        // Simulate network/processing delay
        delay(500L + Random.nextLong(500)) // Simulate 0.5 - 1.0 seconds

        // Construct a simple demo introduction string based on the input
        val demoIntro = """
    Primary Goal Understanding:
    Based on your request "$textInput", the goal is to automate and verify this scenario.

    Test Flow Overview:
    I will simulate launching the relevant application, interacting with elements step-by-step as needed, and checking the final state to determine if the test passes or fails according to your description.
    """.trimIndent()

        log.info("[DEMO] Generated demo introduction.")
        return demoIntro
    }


    private suspend fun getScreenCtxJson(deviceId: String): String {
        val screenCtxJson: String = try {
            withContext(Dispatchers.IO) {
                ADBUtils.runAdbCommand("shell uiautomator dump /sdcard/window_dump.xml", deviceId)
                val screenCtxXml = ADBUtils.runAdbCommand("shell cat /sdcard/window_dump.xml", deviceId)
                screenCtxXml
            }
        } catch (e: Exception) {
            log.error("Failed to get/clean screen context", e)
            "{ \"error\": \"Failed to get screen context\" }" // Provide error JSON
        }
        return screenCtxJson
    }

    private fun getCleanedScreenContext(screenXml: String): String {
        return gson.toJson(Utils.cleanHierarchyDump(screenXml))
    }

    override suspend fun stopRunningTest() {
        val jobToCancel = currentTestJob
        if (jobToCancel?.isActive == true) {
            log.info("stopRunningTest called, cancelling job.")
            isTestRunning = false
            jobToCancel.cancelAndJoin()
            log.info("Test job cancelled and joined.")
        } else {
            log.info("stopRunningTest called, but no active test job found.")
            isTestRunning = false
        }
    }

    // --- Reactive ADB Device Flow Implementation ---
    private val adbDevicesSharedFlow: SharedFlow<List<IDevice>> = callbackFlow {
        println(">>> Starting ADB device monitoring callbackFlow")

        // Define the ADB listener within the flow builder
        val adbListener = object : AndroidDebugBridge.IDeviceChangeListener {
            // Helper function to refresh and send device list into the flow
            fun refreshAndSend(reason: String) {
                println("ADBListener requesting refresh (Reason: $reason)")
                // Launch background task within the flow's scope
                repositoryScope.launch(Dispatchers.IO) {
                    try {
                        val devices = ADBUtils.fetchAdbDevices(project)
                        println("Fetched ${devices.size} devices, sending to flow.")
                        // Sort devices: Emulators last, then by name/serial
                        val sortedDevices =
                            devices.sortedWith(compareBy({ !it.isEmulator }, { it.name ?: it.serialNumber }))
                        // trySend is non-blocking, suitable here
                        val result = trySend(sortedDevices)
                        result.onFailure { throwable ->
                            if (throwable != null) {
                                throwable.printStackTrace()
                                println("Failed to send devices to flow: ${throwable.message}")
                            } else {
                                println("Failed to send devices to flow (channel closed or full)")
                            }
                        }
                    } catch (e: Exception) {
                        e.printStackTrace()
                        println("Error fetching/sending ADB devices in flow: ${e.message}")
                        // Send empty list on error to signal failure to collector
                        val result: ChannelResult<Unit> = trySend(emptyList()) // 1. Call trySend and store result
                        result.onFailure { throwable -> // 2. Call onFailure on the result variable
                            if (throwable != null) {
                                println("Failed to send empty list after error: ${throwable.message}")
                            } else {
                                println("Failed to send empty list after error (channel closed or full)")
                            }
                        }
                    }
                }
            }

            override fun deviceConnected(device: IDevice) {
                refreshAndSend("Device Connected: ${device.serialNumber}")
            }

            override fun deviceDisconnected(device: IDevice) {
                refreshAndSend("Device Disconnected: ${device.serialNumber}")
            }

            override fun deviceChanged(device: IDevice, changeMask: Int) {
                if (changeMask and (IDevice.CHANGE_STATE or IDevice.CHANGE_BUILD_INFO) != 0) {
                    refreshAndSend("Device Changed: ${device.serialNumber}")
                } else {
                    println("Device Changed event ignored (Mask: $changeMask): ${device.serialNumber}")
                }
            }
        }

        // Add the listener (should happen off EDT)
        println("Adding ADB Change Listener")
        AndroidDebugBridge.addDeviceChangeListener(adbListener)

        // Perform initial fetch right after adding listener
        println("Performing initial ADB device fetch for flow")
        adbListener.refreshAndSend("Initial Fetch") // Call the helper

        // awaitClose is crucial for cleanup when the flow collector cancels
        awaitClose {
            println("<<< Stopping ADB device monitoring callbackFlow, removing listener.")
            AndroidDebugBridge.removeDeviceChangeListener(adbListener)
        }
    }
        .flowOn(Dispatchers.IO)
        .distinctUntilChanged()
        .shareIn(
            scope = repositoryScope,
            started = SharingStarted.WhileSubscribed(5000),
            replay = 1
        )

    override fun getAdbDevicesFlow(): Flow<List<IDevice>> {
        return adbDevicesSharedFlow
    }

    override suspend fun saveExecutionLog(logData: TestExecutionLog): Result<String> {
        log.info("Repository delegating save operation to TestLogPersistenceService for log: ${logData.id}")
        val fileResult: Result<File> = persistenceService.saveLog(project, logData)

        return fileResult.map { savedFile ->
            savedFile.absolutePath
        }.onFailure { e ->
            log.error("Persistence service failed to save log ${logData.id} for project ${project.name}", e)
        }
    }

    override suspend fun loadExecutionLogs(): Result<List<TestExecutionLog>> {
        log.info("Repository loading logs from TestLogPersistenceService for project ${project.name}")
        return persistenceService.loadLogsForProject(project)
    }
}